library(shiny)
library(shinyapps)
#library(devtools)
library(ggplot2)
library(googleVis)
library(graphics)
library(grDevices)
#library(XLConnect)
shinyUI(pageWithSidebar(
    
    titlePanel("This is my presentation by BIS's dataset"),
    
    sidebarPanel(
        sliderInput("range", "Select Year",
                    min = 1987, max = 2014, value = c(2007,2014)),
        selectizeInput(
            'errors_shown', 'Select multiple Countries', choices =c(
                #checkboxGroupInput("errors_shown", "Most common errors:", c(
                'All countries'='All countries',
                'Developed countries'='Developed countries',
                'Australia '='Australia ',
                'Austria'='Austria',
                'Belgium'='Belgium',
                'Canada'='Canada',
                'Cyprus'='Cyprus',
                'Denmark '='Denmark ',
                'Estonia'='Estonia',
                'Finland '='Finland ',
                'France'='France',
                'Germany '='Germany ',
                'Greece'='Greece',
                'Iceland'='Iceland',
                'Ireland'='Ireland',
                'Italy'='Italy',
                'Japan'='Japan',
                'Liechtenstein'='Liechtenstein',
                'Luxembourg'='Luxembourg',
                'Malta'='Malta',
                'Netherlands'='Netherlands',
                'New Zealand '='New Zealand ',
                'Norway'='Norway',
                'Portugal '='Portugal ',
                'Slovakia'='Slovakia',
                'Slovenia '='Slovenia ',
                'Spain '='Spain ',
                'Sweden'='Sweden',
                'Switzerland '='Switzerland ',
                'United Kingdom'='United Kingdom',
                'United States '='United States ',
                'Offshore centres'='Offshore centres',
                'Aruba'='Aruba',
                'Bahamas'='Bahamas',
                'Bahrain'='Bahrain',
                'Barbados'='Barbados',
                'Bermuda'='Bermuda',
                'Cayman Islands'='Cayman Islands',
                'Curacao'='Curacao',
                'Gibraltar'='Gibraltar',
                'Hong Kong SAR'='Hong Kong SAR',
                'Lebanon'='Lebanon',
                'Macau SAR'='Macau SAR',
                'Mauritius'='Mauritius',
                'Panama '='Panama ',
                'Singapore'='Singapore',
                'West Indies UK'='West Indies UK',
                'Developing countries'='Developing countries',
                'Africa & Middle East'='Africa & Middle East',
                'Algeria'='Algeria',
                'Angola'='Angola',
                'Benin'='Benin',
                'Cameroon'='Cameroon',
                'Chad'='Chad',
                'Congo'='Congo',
                'Congo Democratic Republic'='Congo Democratic Republic',
                'Cote dIvoire'='Cote dIvoire',
                'Egypt'='Egypt',
                'Gabon'='Gabon',
                'Ghana'='Ghana',
                'Guinea'='Guinea',
                'Iran'='Iran',
                'Iraq'='Iraq',
                'Israel'='Israel',
                'Jordan'='Jordan',
                'Kenya'='Kenya',
                'Kuwait'='Kuwait',
                'Lesotho'='Lesotho',
                'Liberia'='Liberia',
                'Libya'='Libya',
                'Malawi'='Malawi',
                'Mali'='Mali',
                'Morocco'='Morocco',
                'Mozambique'='Mozambique',
                'Namibia'='Namibia',
                'Niger'='Niger',
                'Nigeria'='Nigeria',
                'Oman'='Oman',
                'Qatar'='Qatar',
                'Saudi Arabia'='Saudi Arabia',
                'Senegal'='Senegal',
                'Seychelles'='Seychelles',
                'South Africa'='South Africa',
                'Sudan'='Sudan',
                'Tanzania'='Tanzania',
                'Tunisia'='Tunisia',
                'Uganda'='Uganda',
                'United Arab Emirates'='United Arab Emirates',
                'Yemen'='Yemen',
                'Zambia'='Zambia',
                'Zimbabwe'='Zimbabwe',
                'Asia & Pacific'='Asia & Pacific',
                'Azerbaijan'='Azerbaijan',
                'Bangladesh'='Bangladesh',
                'British Overseas Territories'='British Overseas Territories',
                'Brunei'='Brunei',
                'China'='China',
                'Chinese Taipei'='Chinese Taipei',
                'French Polynesia'='French Polynesia',
                'Georgia'='Georgia',
                'India '='India ',
                'Indonesia'='Indonesia',
                'Kazakhstan'='Kazakhstan',
                'Korea'='Korea',
                'Kyrgyz Republic'='Kyrgyz Republic',
                'Laos'='Laos',
                'Malaysia '='Malaysia ',
                'Myanmar'='Myanmar',
                'Nauru'='Nauru',
                'New Caledonia'='New Caledonia',
                'North Korea'='North Korea',
                'Pakistan'='Pakistan',
                'Papua New Guinea'='Papua New Guinea',
                'Philippines'='Philippines',
                'Sri Lanka'='Sri Lanka',
                'Thailand'='Thailand',
                'Turkmenistan'='Turkmenistan',
                'Uzbekistan'='Uzbekistan',
                'Vietnam'='Vietnam',
                'Europe'='Europe',
                'Belarus'='Belarus',
                'Bulgaria'='Bulgaria',
                'Croatia '='Croatia ',
                'Czech Republic'='Czech Republic',
                'Former Czechoslovakia'='Former Czechoslovakia',
                'Hungary'='Hungary',
                'Latvia'='Latvia',
                'Lithuania'='Lithuania',
                'Macedonia'='Macedonia',
                'Moldova'='Moldova',
                'Poland'='Poland',
                'Romania'='Romania',
                'Russia '='Russia ',
                'Serbia and Montenegro'='Serbia and Montenegro',
                'Soviet Union'='Soviet Union',
                'Turkey'='Turkey',
                'Ukraine'='Ukraine',
                'Latin America & Caribbean'='Latin America & Caribbean',
                'Argentina'='Argentina',
                'Belize'='Belize',
                'Bolivia'='Bolivia',
                'Brazil'='Brazil',
                'Chile'='Chile',
                'Colombia'='Colombia',
                'Costa Rica'='Costa Rica',
                'Cuba'='Cuba',
                'Dominican Republic'='Dominican Republic',
                'Ecuador'='Ecuador',
                'El Salvador'='El Salvador',
                'Grenada'='Grenada',
                'Guatemala'='Guatemala',
                'Haiti'='Haiti',
                'Jamaica'='Jamaica',
                'Mexico'='Mexico',
                'Nicaragua'='Nicaragua',
                'Paraguay'='Paraguay',
                'Peru'='Peru',
                'Surinam'='Surinam',
                'Trinidad & Tobago'='Trinidad & Tobago',
                'Uruguay'='Uruguay',
                'Venezuela'='Venezuela',
                'Int. organisations'='Int. organisations'
            ), multiple = TRUE
        )),
    
    
    tabsetPanel(type = "tabs", 
                tabPanel("Graph", plotOutput("freqPlot")), 
                tabPanel("Table",
                         dataTableOutput("mytable1")
                ),
                tabPanel("Summary statistics", 
                         helpText('Summary statistics for range, if chosen, or for all series if nothing is chosen'),
                         verbatimTextOutput("summary")),
                tabPanel("Geographical map",htmlOutput("gvis"))
    )         

))